// example/components/src/lib/components/LearnMore.svelte
<!--
@component

# LearnMore

Render a learn more link.

## Usage:
  ```html
  <LearnMore />
```
-->

<script lang="ts">
  import { ArrowRight } from "@lucide/svelte";
  import { _ } from "svelte-i18n";
</script>

<div class="learn-more">
  <a
    href="https://docs.frak.id/components"
    target="_blank"
    rel="noreferrer"
    class="learn-more-link"
  >
    {$_("common.learnMore")}
    <ArrowRight size={16} />
  </a>
</div>

<style>
  .learn-more {
    text-align: center;
  }

  .learn-more-link {
    color: #0066ff;
    text-decoration: none;
    font-size: 14px;
    font-weight: 500;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
  }
</style>

// example/showcase/src/components/landing/LearnMore.tsx
import { ArrowRight } from "lucide-react";
import { useTranslation } from "react-i18next";
import styles from "./LearnMore.module.css";

export function LearnMore() {
    const { t } = useTranslation();

    return (
        <div className={styles.learnMore}>
            <a
                href="https://docs.frak.id/components"
                target="_blank"
                rel="noreferrer"
                className={styles.learnMoreLink}
            >
                {t("common.learnMore")}
                <ArrowRight size={16} />
            </a>
        </div>
    );
}
